import 'dart:convert';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:excel/excel.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';
import '../models/models.dart';

class ExportService {
  static String generateWhatsAppText(FieldEntry entry) {
    var materialLines = <String>[];
    for (var i = 0; i < entry.materials.length; i++) {
      final mat = entry.materials[i];
      final serial = (i + 1).toString().padLeft(2, '0');
      var line = '*$serial ${mat.name}*';
      if (mat.requested.isNotEmpty) line += ' | Req: ${mat.requested}';
      if (mat.received.isNotEmpty) line += ' | Rec: ${mat.received}';
      if (mat.used.isNotEmpty) line += ' | Used: ${mat.used}';
      if (mat.remaining.isNotEmpty) line += ' | Rem: ${mat.remaining}';
      if (mat.comment.isNotEmpty) line += ' | *Comment:* ${mat.comment}';
      materialLines.add(line);
    }
    final mrf = entry.mrfNumber.isNotEmpty ? '*MRF:* ${entry.mrfNumber}\n' : '';
    final drr = entry.drrCode.isNotEmpty ? '*DRR:* ${entry.drrCode}\n' : '';
    final schemes = entry.schemes.isNotEmpty
        ? '*Scheme(s):* ${entry.schemes.join(', ')}'
        : '';
    return '''
*Field Material Entry*
----------------------------------
*Date:* ${entry.date}
*Checker:* ${entry.checker}
*TM:* ${entry.tm}
*Block:* ${entry.block} *Sub:* ${entry.subBlock}
$mrf$drr$schemes

*--- Materials Tracked ---*
${materialLines.join('\n')}
----------------------------------
Generated by Field Material App''';
  }

  static Future<void> shareViaWhatsApp(FieldEntry entry) async {
    final text = generateWhatsAppText(entry);
    final url = 'https://wa.me/?text=${Uri.encodeComponent(text)}';
    final parsedUrl = Uri.parse(url);
    if (await canLaunchUrl(parsedUrl)) {
      await launchUrl(parsedUrl, mode: LaunchMode.externalApplication);
    } else {
      await Share.share(text);
    }
  }

  static String generateCsvData(List<FieldEntry> entries) {
    final buffer = StringBuffer();
    buffer.writeln(
        'Checker,TM,Block,Sub-Block,MRF Number,DRR-CODE,Type Scheme,Material,Requested,Received,Used,Remaining,Comment,Date');
    for (var ent in entries) {
      final schemesEscaped = ent.schemes.join('; ').replaceAll('"', '""');
      for (var mat in ent.materials) {
        final row = [
          '"${ent.checker.replaceAll('"', '""')}"',
          '"${ent.tm.replaceAll('"', '""')}"',
          '"${ent.block.replaceAll('"', '""')}"',
          '"${ent.subBlock.replaceAll('"', '""')}"',
          '"${ent.mrfNumber.replaceAll('"', '""')}"',
          '"${ent.drrCode.replaceAll('"', '""')}"',
          '"$schemesEscaped"',
          '"${mat.name.replaceAll('"', '""')}"',
          mat.requested,
          mat.received,
          mat.used,
          mat.remaining,
          '"${mat.comment.replaceAll('"', '""')}"',
          '"${ent.date}"'
        ];
        buffer.writeln(row.join(','));
      }
    }
    return buffer.toString();
  }

  static Future<void> exportCsvSheet(List<FieldEntry> entries) async {
    final csv = generateCsvData(entries);
    if (kIsWeb) {
      await Share.share(csv, subject: 'Field Materials CSV');
    } else {
      final tempDir = await getTemporaryDirectory();
      final file = File('${tempDir.path}/Field_Material_Entries.csv');
      await file.writeAsString(csv);
      await Share.shareXFiles([XFile(file.path)],
          subject: 'Field Materials Export');
    }
  }

  static Future<void> exportXlsxSheet(List<FieldEntry> entries) async {
    var excel = Excel.createExcel();
    var sheet = excel['Sheet1'];

    sheet.appendRow([
      TextCellValue('Checker'),
      TextCellValue('TM'),
      TextCellValue('Block'),
      TextCellValue('Sub-Block'),
      TextCellValue('MRF Number'),
      TextCellValue('DRR-CODE'),
      TextCellValue('Type Scheme'),
      TextCellValue('Material'),
      TextCellValue('Requested'),
      TextCellValue('Received'),
      TextCellValue('Used'),
      TextCellValue('Remaining'),
      TextCellValue('Comment'),
      TextCellValue('Date')
    ]);

    for (var ent in entries) {
      final schemesJoined = ent.schemes.join('; ');
      for (var mat in ent.materials) {
        sheet.appendRow([
          TextCellValue(ent.checker),
          TextCellValue(ent.tm),
          TextCellValue(ent.block),
          TextCellValue(ent.subBlock),
          TextCellValue(ent.mrfNumber),
          TextCellValue(ent.drrCode),
          TextCellValue(schemesJoined),
          TextCellValue(mat.name),
          TextCellValue(mat.requested),
          TextCellValue(mat.received),
          TextCellValue(mat.used),
          TextCellValue(mat.remaining),
          TextCellValue(mat.comment),
          TextCellValue(ent.date)
        ]);
      }
    }

    final bytes = excel.encode();
    if (bytes != null) {
      if (kIsWeb) {
        await Share.share('Export completed.', subject: 'Excel Export');
      } else {
        final tempDir = await getTemporaryDirectory();
        final file = File('${tempDir.path}/Field_Materials.xlsx');
        await file.writeAsBytes(bytes);
        await Share.shareXFiles([XFile(file.path)],
            subject: 'Field Materials Excel');
      }
    }
  }

  static Future<void> exportJsonSheet(List<FieldEntry> entries) async {
    final raw = jsonEncode(entries.map((e) => e.toJson()).toList());
    if (kIsWeb) {
      await Share.share(raw, subject: 'Field Materials JSON');
    } else {
      final tempDir = await getTemporaryDirectory();
      final file = File('${tempDir.path}/Field_Material_Entries.json');
      await file.writeAsString(raw);
      await Share.shareXFiles([XFile(file.path)],
          subject: 'Field Materials JSON');
    }
  }
}
