name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'latest'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Clean Gradle cache
        run: cd android && ./gradlew clean

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: field-material-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
